-- informação da edição
create table if not exists edicoes_marvel (
    id_edicao text,
    serie text,
    edicao text,
    lancamento text,
    escritor text,
    desenhista text,
    arte_finalista text,
    colorista text,
    letrista text,
    editor text,
    primary key (id_edicao)
);

insert or ignore into edicoes_marvel (id_edicao, serie, edicao, lancamento, escritor, desenhista, arte_finalista, colorista, letrista, editor)
values (
    'fab_vingadores_01',
    'os fabulosos vingadores',
    '01',
    '2012',
    'rick remender',
    'john cassaday',
    'john cassaday',
    'laura martin',
    'chris eliopoulos',
    'tom brevoort'
);

-- informações de personagens
create table if not exists personagens_marvel (
    id_personagem text,
    universo text,
    nome_civil text,
    alter_ego text,
    outros_pseudonimos text,
    alinhamento text,
    especie text,
    genero text,
    primary key (id_personagem)
);

insert or ignore into personagens_marvel (id_personagem, universo, nome_civil, alter_ego, outros_pseudonimos, alinhamento, especie, genero)
values
('johann_shmidt', 'marvel', 'johann shmidt', 'caveira vermelha', 'n/a', 'vilão', 'humano (aprimorado)', 'masculino'),
('dominikos_petrakis', 'marvel', 'dominikos petrakis', 'avalanche', 'n/a', 'vilão', 'mutante', 'masculino'),
('logan', 'marvel', 'james "logan" howlett', 'wolverine', 'n/a', 'herói', 'mutante', 'masculino'),
('charles_xavier', 'marvel', 'charles xavier', 'professor x', 'n/a', 'herói', 'mutante', 'masculino'),
('hank_mccoy', 'marvel', 'henry "hank" mccoy', 'fera', 'n/a', 'herói', 'mutante', 'masculino'),
('rachel_grey', 'marvel', 'rachel grey-summers', 'n/a', 'n/a', 'herói', 'mutante', 'feminino'),
('kitty_pride', 'marvel', 'katherine "kitty" pride', 'lince negra', 'n/a', 'herói', 'mutante', 'feminino'),
('ororo_munroe', 'marvel', 'ororo munroe', 'tempestade', 'n/a', 'herói', 'mutante', 'feminino'),
('maria_hill', 'marvel', 'maria hill', 'n/a', 'n/a', 'herói', 'humano', 'feminino'),
('alex_summers', 'marvel', 'alexander "alex" summers', 'destrutor', 'n/a', 'herói', 'mutante', 'masculino'),
('steve_rogers', 'marvel', 'steven "steve" rogers', 'capitão américa', 'n/a', 'herói', 'humano (aprimorado)', 'masculino'),
('thor_odinson', 'marvel', 'thor odinson', 'thor', 'n/a', 'herói', 'asgardiano', 'masculino'),
('jean_grey', 'marvel', 'jean grey', 'fenix', 'n/a', 'herói', 'mutante', 'feminino'),
('bobby_drake', 'marvel', 'robert "bobby" drake', 'homem de gelo', 'n/a', 'herói', 'mutante', 'masculino'),
('warren_worthington', 'marvel', 'warren worthington III', 'anjo', 'n/a', 'herói', 'mutante', 'masculino'),
('scott_summers', 'marvel', 'scott summers', 'ciclope', 'n/a', 'herói', 'mutante', 'masculino'),
('erik_lehnsherr', 'marvel', 'erik lehnsherr', 'magneto', 'max eisenhardt', 'neutro', 'mutante', 'masculino'),
('inseto', 'marvel', 'n/a', 'inseto', 'n/a', 'vilão', 'mutante', 'masculino'),
('cara_de_bode', 'marvel', 'n/a', 'cara-de-bode', 'n/a', 'vilão', 'mutante', 'feminino'),
('anna_marie', 'marvel', 'anna marie lebeau', 'vampira', 'n/a', 'herói', 'mutante', 'feminino'),
('joao_honesto', 'marvel', 'n/a', 'joão honesto', 'n/a', 'vilão', 'mutante', 'masculino'),
('vento_cortante', 'marvel', 'n/a', 'vento cortante', 'n/a', 'vilão', 'mutante', 'feminino'),
('wanda_maximoff', 'marvel', 'wanda maximoff', 'feiticeira escarlate', 'n/a', 'herói', 'mutante', 'feminino'),
('danielle_petrakis', 'marvel', 'danielle petrakis', 'água dançante', 'n/a', 'vilão', 'mutante', 'feminino'),
('mzee', 'marvel', 'n/a', 'mzee', 'n/a', 'vilão', 'mutante', 'masculino');

-- adição dos painéis
create table if not exists paineis_marvel (
    id_painel text,
    id_edicao text,
    personagens text,
    vozes text,
    enquadramento text,
    primary key (id_painel, id_edicao)
);

insert or ignore into paineis_marvel (id_painel, id_edicao, personagens, vozes, enquadramento)
values 
('pn001', 'fab_vingadores_01', 'dominikos_petrakis', 'f_johann_shmidt(2), mudo_dominikos_petrakis', 'primeiro plano'),
('pn002', 'fab_vingadores_01', 'dominikos_petrakis', 'f_johann_shmidt(3), mudo_dominikos_petrakis', 'primeiro plano'),
('pn003', 'fab_vingadores_01', 'dominikos_petrakis', 'f_johann_shmidt(3), mudo_dominikos_petrakis', 'primeiro plano'),
('pn004', 'fab_vingadores_01', 'dominikos_petrakis', 'f_johann_shmidt(4), mudo_dominikos_petrakis', 'primeiro plano'),
('pn005', 'fab_vingadores_01', 'dominikos_petrakis', 'f_johann_shmidt(3), mudo_dominikos_petrakis', 'primeiro plano'),
('pn006', 'fab_vingadores_01', 'logan', 'n_johann_shmidt(3), mudo_logan', 'corpo inteiro'),
('pn007', 'fab_vingadores_01', 'logan', 'n_charles_xavier(1), mudo_logan', 'primeiro plano'),
('pn008', 'fab_vingadores_01', 'charles_xavier, logan', 'f_charles_xavier(3), mudo_logan', 'plano médio'),
('pn009', 'fab_vingadores_01', 'logan', 'n_charles_xavier(1), mudo_logan, f_anna_marie(1)', 'primeiro plano'),
('pn010', 'fab_vingadores_01', 'logan, anna_marie', 'mudo_logan, f_anna_marie(1)', 'plano médio'),
('pn011', 'fab_vingadores_01', 'logan, anna_marie', 'mudo_logan, mudo_anna_marie', 'panorâmico'),
('pn012', 'fab_vingadores_01', 'logan, anna_marie', 'mudo_logan, mudo_anna_marie', 'panorâmico'),
('pn013', 'fab_vingadores_01', 'logan', 'mudo_logan', 'plano médio'),
('pn014', 'fab_vingadores_01', 'logan', 'f_logan(2)', 'plano médio'),
('pn015', 'fab_vingadores_01', 'logan', 'f_logan(1)', 'primeiro plano'),
('pn016', 'fab_vingadores_01', 'hank_mccoy, rachel_grey, kitty_pride, ororo_munroe', 'f_logan(1), mudo_hank_mccoy, mudo_rachel_grey, mudo_kitty_pride, mudo_ororo_munroe', 'plano médio'),
('pn017', 'fab_vingadores_01', 'logan', 'f_logan(3)', 'sobreposição'),
('pn018', 'fab_vingadores_01', 'maria_hill, alex_summers', 'n_logan(1), f_maria_hill(1), f_alex_summers(1)', 'panorâmico'),
('pn019', 'fab_vingadores_01', 'logan', 'f_logan(4)', 'primeiro plano'),
('pn020', 'fab_vingadores_01', 'alex_summers, maria_hill', 'n_logan(4), mudo_alex_summers, mudo_maria_hill', 'plano médio'),
('pn021', 'fab_vingadores_01', 'alex_summers, maria_hill, scott summers', 'n_logan(3), mudo_alex_summers, mudo_maria_hill, mudo_scott_summers', 'plano médio'),
('pn022', 'fab_vingadores_01', 'logan', 'f_logan(2)', 'primeiro plano'),
('pn023', 'fab_vingadores_01', 'scott_summers, alex_summers', 'n_logan(2), f_scott_summers(1), f_alex_summers(1)', 'corpo inteiro'),
('pn024', 'fab_vingadores_01', 'logan', 'f_logan(4)', 'primeiro plano'),
('pn025', 'fab_vingadores_01', 'logan', 'f_logan(3)', 'plano médio'),
('pn026', 'fab_vingadores_01', 'logan', 'f_logan(1)', 'primeiro plano'),
('pn027', 'fab_vingadores_01', 'erik_lehnsherr', 'mudo_erik_lehnsherr, f_logan(2)', 'plano médio'),
('pn028', 'fab_vingadores_01', 'logan', 'f_logan(1)', 'primeiro plano'),
('pn029', 'fab_vingadores_01', 'hank_mccoy, kitty_pride, ororo_munroe, logan', 'mudo_hank_mccoy, mudo_kitty_pride, mudo_ororo_munroe, f_logan(1)', 'panorâmico'),
('pn030', 'fab_vingadores_01', 'scott_summers, alex_summers', 'mudo_scott_summers, f_alex_summers(1)', 'primeiro plano'),
('pn031', 'fab_vingadores_01', 'scott_summers', 'mudo_scott_summers', 'primeiro plano'),
('pn032', 'fab_vingadores_01', 'bobby_drake, jean_grey, warren_worthington, charles_xavier', 'mudo_bobby_drake, mudo_jean_grey, mudo_warren_worthington, f_charles_xavier(1)', 'plano médio'),
('pn033', 'fab_vingadores_01', 'scott_summers, alex_summers', 'mudo_scott_summers, f_alex_summers(2)', 'corpo inteiro'),
('pn034', 'fab_vingadores_01', 'scott_summers, alex_summers', 'f_scott_summers(1), f_alex_summers(2)', 'plano médio'),
('pn035', 'fab_vingadores_01', 'scott_summers', 'f_scott_summers(3)', 'primeiro plano'),
('pn036', 'fab_vingadores_01', 'scott_summers, alex_summers', 'f_scott_summers(1), f_alex_summers(3)', 'corpo inteiro'),
('pn037', 'fab_vingadores_01', 'alex_summers', 'f_alex_summers(3)', 'primeiro plano'),
('pn038', 'fab_vingadores_01', 'scott_summers, alex_summers', 'f_scott_summers(1), f_alex_summers(3)', 'plano médio'),
('pn039', 'fab_vingadores_01', 'scott_summers', 'f_scott_summers(1)', 'primeiro plano'),
('pn040', 'fab_vingadores_01', 'scott_summers, alex_summers', 'mudo_scott_summers, f_alex_summers(2)', 'plano médio'),
('pn041', 'fab_vingadores_01', 'scott_summers, alex_summers', 'mudo_scott_summers, f_alex_summers(1)', 'primeiro plano'),
('pn042', 'fab_vingadores_01', 'alex_summers', 'mudo_alex_summers, f_steve_rogers(1)', 'sobreposição'),
('pn043', 'fab_vingadores_01', 'steve_rogers, thor_odinson', 'f_steve_rogers(1), f_thor_odinson(2)', 'plano médio'),
('pn044', 'fab_vingadores_01', 'n/a', 'n_steve_rogers(1)', 'panorâmico'),
('pn045', 'fab_vingadores_01', 'steve_rogers, thor_odinson, alex_summers', 'f_steve_rogers(1), f_thor_odinson(2), f_alex_summers(1)', 'corpo inteiro'),
('pn046', 'fab_vingadores_01', 'steve_rogers, thor_odinson, alex_summers', 'f_alex_summers(2), f_steve_rogers(2), mudo_thor_odinson', 'plano médio'),
('pn047', 'fab_vingadores_01', 'n/a', 'n_steve_rogers(1)', 'panorâmico'),
('pn048', 'fab_vingadores_01', 'steve_rogers, thor_odinson, alex_summers', 'f_steve_rogers(2), f_alex_summers(1), mudo_thor_odinson', 'corpo inteiro'),
('pn049', 'fab_vingadores_01', 'steve_rogers', 'f_steve_rogers(4)', 'primeiro plano'),
('pn050', 'fab_vingadores_01', 'figurantes, dominikos_petrakis', 'n_steve_rogers(2), f_figurantes(2), mudo_dominikos_petrakis', 'corpo inteiro'),
('pn051', 'fab_vingadores_01', 'figurantes, dominikos_petrakis', 'n_steve_rogers(3), f_figurantes(1), mudo_dominikos_petrakis', 'primeiro plano'),
('pn052', 'fab_vingadores_01', 'dominikos_petrakis', 'f_dominikos_petrakis(1)', 'primeiro plano'),
('pn053', 'fab_vingadores_01', 'steve_rogers, alex_summers', 'f_steve_rogers(2), f_alex_summers(1)', 'primeiro plano'),
('pn054', 'fab_vingadores_01', 'steve_rogers, alex_summers', 'f_steve_rogers(1), f_alex_summers(2)', 'primeiro plano'),
('pn055', 'fab_vingadores_01', 'dominikos_petrakis, figurantes', 'n_alex_summers(1), f_dominikos_petrakis(1), f_figurantes(4)', 'panorâmico'),
('pn056', 'fab_vingadores_01', 'alex_summers, thor_odinson, steve_rogers', 'mudo_alex_summers, mudo_thor_odinson, f_steve_rogers(1)', 'plano médio'),
('pn057', 'fab_vingadores_01', 'dominikos_petrakis, figurantes', 'f_dominikos_petrakis(3), f_figurantes(4)', 'corpo inteiro'),
('pn058', 'fab_vingadores_01', 'thor_odinson', 'mudo_thor_odinson', 'plano médio'),
('pn059', 'fab_vingadores_01', 'steve_rogers, alex_summers', 'n_steve_rogers(2), f_steve_rogers(1), mudo_alex_summers', 'plano médio'),
('pn060', 'fab_vingadores_01', 'steve_rogers, alex_summers', 'n_steve_rogers(1), mudo_steve_rogers, mudo_alex_summers', 'corpo inteiro'),
('pn061', 'fab_vingadores_01', 'thor_odinson', 'n_steve_rogers(1), mudo_thor_odinson', 'corpo inteiro'),
('pn062', 'fab_vingadores_01', 'steve_rogers, dominikos_petrakis', 'n_steve_rogers(1), f_steve_rogers(2), mudo_dominikos_petrakis', 'corpo inteiro'),
('pn063', 'fab_vingadores_01', 'steve_rogers, dominikos_petrakis', 'n_steve_rogers(2), mudo_steve_rogers, f_dominikos_petrakis(2)', 'corpo inteiro'),
('pn064', 'fab_vingadores_01', 'steve_rogers, dominikos_petrakis', 'n_steve_rogers(2), mudo_steve_rogers, f_dominikos_petrakis(1)', 'corpo inteiro'),
('pn065', 'fab_vingadores_01', 'steve_rogers', 'n_steve_rogers(1), mudo_steve_rogers', 'sobreposição'),
('pn066', 'fab_vingadores_01', 'figurantes', 'f_figurantes(4)', 'panorâmico'),
('pn067', 'fab_vingadores_01', 'alex_summers', 'n_wanda_maximoff(1), f_alex_summers(1)', 'corpo inteiro'),
('pn068', 'fab_vingadores_01', 'thor_odinson', 'n_wanda_maximoff(1), mudo_thor_odinson', 'corpo inteiro'),
('pn069', 'fab_vingadores_01', 'alex_summers', 'n_wanda_maximoff(1), mudo_alex_summers', 'plano médio'),
('pn070', 'fab_vingadores_01', 'steve_rogers', 'n_wanda_maximoff(1), mudo_steve_rogers', 'plano médio'),
('pn071', 'fab_vingadores_01', 'n/a', 'n_wanda_maximoff(3)', 'primeiro plano'),
('pn072', 'fab_vingadores_01', 'wanda_maximoff', 'n_wanda_maximoff(6), mudo_wanda_maximoff', 'primeiro plano'),
('pn073', 'fab_vingadores_01', 'wanda_maximoff', 'n_wanda_maximoff(5), mudo_wanda_maximoff', 'corpo inteiro'),
('pn074', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'n_wanda_maximoff(1), mudo_wanda_maximoff, f_anna_marie(4)', 'corpo inteiro'),
('pn075', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'f_wanda_maximoff(3), f_anna_marie(1)', 'plano médio'),
('pn076', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'f_wanda_maximoff(3), f_anna_marie(1)', 'corpo inteiro'),
('pn077', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'f_wanda_maximoff(1), f_anna_marie(2)', 'primeiro plano'),
('pn078', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'mudo_wanda_maximoff, f_anna_marie(4)', 'primeiro plano'),
('pn079', 'fab_vingadores_01', 'wanda_maximoff', 'f_wanda_maximoff(3)', 'primeiro plano'),
('pn080', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'mudo_wanda_maximoff, mudo_anna_marie', 'plano médio'),
('pn081', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'f_wanda_maximoff(2), f_anna_marie(2)', 'plano médio'),
('pn082', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'mudo_wanda_maximoff, f_anna_marie(2)', 'primeiro plano'),
('pn083', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'mudo_wanda_maximoff, f_anna_marie(2)', 'plano médio'),
('pn084', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'mudo_wanda_maximoff, mudo_anna_marie', 'página inteira'),
('pn085', 'fab_vingadores_01', 'wanda_maximoff, anna_marie', 'f_wanda_maximoff(1), f_anna_marie(1)', 'sobreposição'),
('pn086', 'fab_vingadores_01', 'danielle_petrakis, inseto, cara_de_bode, mzee, vento_cortante', 'n_wanda_maximoff(1), mudo_danielle_petrakis, mudo_inseto, mudo_cara_de_bode, mudo_mzee, mudo_vento_cortante', 'corpo inteiro'),
('pn087', 'fab_vingadores_01', 'wanda_maximoff, anna_marie, vento_cortante', 'f_wanda_maximoff(1), mudo_anna_marie, f_vento_cortante(1)', 'corpo inteiro'),
('pn088', 'fab_vingadores_01', 'inseto', 'f_inseto(2)', 'plano médio'),
('pn089', 'fab_vingadores_01', 'anna_marie, inseto', 'mudo_anna_marie, f_inseto(2)', 'corpo inteiro'),
('pn090', 'fab_vingadores_01', 'anna_marie, wanda_maximoff, inseto', 'mudo_anna_marie, f_wanda_maximoff(1), mudo_inseto', 'plano médio'),
('pn091', 'fab_vingadores_01', 'anna_marie, wanda_maximoff', 'f_anna_marie(1), f_wanda_maximoff(1)', 'primeiro plano'),
('pn092', 'fab_vingadores_01', 'mzee', 'f_mzee(2)', 'plano médio'),
('pn093', 'fab_vingadores_01', 'danielle_petrakis', 'mudo_danielle_petrakis', 'corpo inteiro'),
('pn094', 'fab_vingadores_01', 'n/a', 'n/a', 'panorâmico'),
('pn095', 'fab_vingadores_01', 'n/a', 'f_johann_shmidt(1)', 'panorâmico'),
('pn096', 'fab_vingadores_01', 'joao_honesto, johann_shmidt', 'f_joao_honesto(4), f_johann_shmidt(1)', 'plano médio'),
('pn097', 'fab_vingadores_01', 'joao_honesto', 'f_johann_shmidt(1), mudo_joao_honesto', 'plano médio'),
('pn098', 'fab_vingadores_01', 'johann_shmidt', 'f_johann_shmidt(3)', 'primeiro plano'),
('pn099', 'fab_vingadores_01', 'johann_shmidt, charles_xavier', 'f_johann_shmidt(1), mudo_charles_xavier', 'página inteira');